name: WDLCompanionASkyBlockSupport
main: wdl.askyblock.ASkyBlockSupportPlugin
version: 0.0.3-SNAPSHOT
author: Pokechu22
depend: [WDLCompanion]
softdepend: [ASkyBlock, AcidIsland]
website: http://dev.bukkit.org/bukkit-plugins/wdl-companion-askyblock-support/
description: Adds a new WDLCompanion Chunk Override type, 'ASkyBlock island', which allows a player to use World Downloader on their own island.